// <auto-generated />
namespace UTM.Keto.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class db22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db22));
        
        string IMigrationMetadata.Id
        {
            get { return "202505130534171_db22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
